POSTGRES_USERNAME: "postgres"
POSTGRES_PASSWORD: "postgres"
POSTGRES_URL: "jdbc:postgresql://localhost:5432/postgres"

spring:
  application:
    name: auth-server
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: ${MYSQL_USERNAME:root} # update username
    #    password: ${MYSQL_PASSWORD:123456} # update password
#    url: jdbc:mysql://localhost:3306/integrated_oauth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME:postgres} # update username
    password: ${POSTGRES_PASSWORD:postgres} # update password
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    fail-on-missing-locations: true


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
