apiVersion: v1
kind: Service
metadata:
  namespace: nurserystore
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nurserystore-mysql-db
  name: nurserystore-mysql-db
spec:
  ports:
    - name: "3306-tcp"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: nurserystore-mysql-db
