apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nurserystore
  labels:
    io.kompose.service: nurserystore-db-volume
  name: nurserystore-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
