apiVersion: v1
kind: Service
metadata:
  namespace: nurserystore
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nurserystore-catalog-service
  name: nurserystore-catalogue-service
spec:
  ports:
    - name: "6001"
      port: 6001
      targetPort: 6001
  selector:
    io.kompose.service: nurserystore-catalog-service
