apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: booksture-influxdb-volume
  name: booksture-influxdb-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
