apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bookstore-order-service
  name: bookstore-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookstore-order-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: bookstore-order-service
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "7001"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: ZIPKIN_HOST
              value: bookstore-zipkin:9411
          image: bookstore-order-service
          name: bookstore-order-service
          ports:
            - containerPort: 7001
              protocol: TCP
      hostname: bookstore-order-service
      restartPolicy: Always
