apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bookstore-zuul-api-gateway-server
  name: bookstore-zuul-api-gateway-server
spec:
  ports:
    - name: "8765"
      port: 8765
      targetPort: 8765
  selector:
    io.kompose.service: bookstore-zuul-api-gateway-server
